---
title: "BV_merge"
author: "Helen Payne"
date: "2024-09-17"
output: html_document
---
###ANGELO COAST###
```{r}
#load data
BV_AC22<-read.csv("AC22_bhat.Donor.mu.csv")
BV_AC23<-read.csv("AC23_bhat.Donor.mu.csv")
```

```{r}
library(dplyr)

# rename column names
BV_AC22 <- BV_AC22 %>%
  rename(Donor = 1, BV_AC22 = 2)

BV_AC23 <- BV_AC23 %>%
  rename(Donor = 1, BV_AC23 = 2)
```


```{r}
library(dplyr)
library(stringr)

#simplifying the donor label
BV_AC22 <- BV_AC22 %>%
  mutate(Donor = str_sub(Donor, -3))

BV_AC23 <- BV_AC23 %>%
  mutate(Donor = str_sub(Donor, -3))
```

```{r}
library(dplyr)

#merge the dfs 
AC_BV <- full_join(BV_AC22, BV_AC23)

write.csv(AC_BV, "AC_BV.csv")
```

###BODEGA BAY###
```{r}
#load data
BV_BB22<-read.csv("BB22_bhat.Donor.mu.csv")
BV_BB23<-read.csv("BB23_bhat.Donor.mu.csv")
```

```{r}
# rename column names
BV_BB22 <- BV_BB22 %>%
  rename(Donor = 1, BV_BB22 = 2)

BV_BB23 <- BV_BB23 %>%
  rename(Donor = 1, BV_BB23 = 2)
```


```{r}

#simplifying the donor label
BV_BB22 <- BV_BB22 %>%
  mutate(Donor = str_sub(Donor, -3))

BV_BB23 <- BV_BB23 %>%
  mutate(Donor = str_sub(Donor, -3))
```

```{r}

#merge the dfs 
BB_BV <- full_join(BV_BB22, BV_BB23)
write.csv(BB_BV, "BB_BV.csv")
```

###BLUE OAK###
```{r}
#load data
BV_BO22<-read.csv("BO22_bhat.Donor.mu.csv")
BV_BO23<-read.csv("BO23_bhat.Donor.mu.csv")
```

```{r}
# rename column names
BV_BO22 <- BV_BO22 %>%
  rename(Donor = 1, BV_BO22 = 2)

BV_BO23 <- BV_BO23 %>%
  rename(Donor = 1, BV_BO23 = 2)
```


```{r}

#simplifying the donor label
BV_BO22 <- BV_BO22 %>%
  mutate(Donor = str_sub(Donor, -3))

BV_BO23 <- BV_BO23 %>%
  mutate(Donor = str_sub(Donor, -3))
```

```{r}

#merge the dfs 
BO_BV <- full_join(BV_BO22, BV_BO23)
write.csv(BO_BV, "BO_BV.csv")
```

###HASTINGS###
```{r}
#load data
BV_HR22<-read.csv("HR22_bhat.Donor.mu.csv")
BV_HR23<-read.csv("HR23_bhat.Donor.mu.csv")
```

```{r}
# rename column names
BV_HR22 <- BV_HR22 %>%
  rename(Donor = 1, BV_HR22 = 2)

BV_HR23 <- BV_HR23 %>%
  rename(Donor = 1, BV_HR23 = 2)
```


```{r}

#simplifying the donor label
BV_HR22 <- BV_HR22 %>%
  mutate(Donor = str_sub(Donor, -3))

BV_HR23 <- BV_HR23 %>%
  mutate(Donor = str_sub(Donor, -3))
```

```{r}

#merge the dfs 
HR_BV <- full_join(BV_HR22, BV_HR23)
write.csv(HR_BV, "HR_BV.csv")
```
###Breeding values- Figures###
```{r}
#Figure 3: Breeding values and corelation coefficients
###One site between years

library(ggplot2)
library(patchwork)

#load data
AC_BV<-read.csv("AC_BV.csv")

#plot AC breeding values between years
AC <- ggplot(AC_BV, aes(x=BV_AC22, y=BV_AC23)) +
  geom_point(size=2, color="black") +
  ylab("AC 2023") +
  xlab("AC 2022") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_text(face="bold", color="black", size=12),
        axis.text.y = element_text(face="bold", color="black", size=12),
        axis.line.x = element_line(color="black", linewidth=0.4),  # Updated from size to linewidth
        axis.line.y = element_line(color="black", linewidth=0.4),  # Updated from size to linewidth
        axis.title.y = element_text(size=14, face="bold"),
        axis.title.x = element_text(size=14, face="bold"),
        panel.border = element_rect(colour = "black", fill=NA, linewidth=0.4))  # Updated from size to linewidth

# Display the plot
print(AC)

#calculate the correlation coefficient
cor.test(AC_BV$BV_AC22, AC_BV$BV_AC23, method="pearson")

#load data
BB_BV<-read.csv("BB_BV.csv")

#plot BB breeding values between years
BB <- ggplot(BB_BV, aes(x=BV_BB22, y=BV_BB23)) +
  geom_point(size=2, color="black") +
  ylab("BB 2023") +
  xlab("BB 2022") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_text(face="bold", color="black", size=12),
        axis.text.y = element_text(face="bold", color="black", size=12),
        axis.line.x = element_line(color="black", linewidth=0.4),  # Updated from size to linewidth
        axis.line.y = element_line(color="black", linewidth=0.4),  # Updated from size to linewidth
        axis.title.y = element_text(size=14, face="bold"),
        axis.title.x = element_text(size=14, face="bold"),
        panel.border = element_rect(colour = "black", fill=NA, linewidth=0.4))  # Updated from size to linewidth

# Display the plot
print(BB)

#calculate the correlation coefficient
cor.test(BB_BV$BV_BB22, BB_BV$BV_BB23, method="pearson")

#load data
HR_BV<-read.csv("HR_BV.csv")

#plot BB breeding values between years
HR <- ggplot(HR_BV, aes(x=BV_HR22, y=BV_HR23)) +
  geom_point(size=2, color="black") +
  ylab("HR 2023") +
  xlab("HR 2022") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_text(face="bold", color="black", size=12),
        axis.text.y = element_text(face="bold", color="black", size=12),
        axis.line.x = element_line(color="black", linewidth=0.4),  # Updated from size to linewidth
        axis.line.y = element_line(color="black", linewidth=0.4),  # Updated from size to linewidth
        axis.title.y = element_text(size=14, face="bold"),
        axis.title.x = element_text(size=14, face="bold"),
        panel.border = element_rect(colour = "black", fill=NA, linewidth=0.4))  # Updated from size to linewidth

# Display the plot
print(HR)

#calculate the correlation coefficient
cor.test(HR_BV$BV_HR22, HR_BV$BV_HR23, method="pearson")

#load data
BO_BV<-read.csv("BO_BV.csv")

#plot BB breeding values between years
BO <- ggplot(BO_BV, aes(x=BV_BO22, y=BV_BO23)) +
  geom_point(size=2, color="black") +
  ylab("BO 2023") +
  xlab("BO 2022") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_text(face="bold", color="black", size=12),
        axis.text.y = element_text(face="bold", color="black", size=12),
        axis.line.x = element_line(color="black", linewidth=0.4),  # Updated from size to linewidth
        axis.line.y = element_line(color="black", linewidth=0.4),  # Updated from size to linewidth
        axis.title.y = element_text(size=14, face="bold"),
        axis.title.x = element_text(size=14, face="bold"),
        panel.border = element_rect(colour = "black", fill=NA, linewidth=0.4))  # Updated from size to linewidth

# Display the plot
print(BO)

#calculate the correlation coefficient
cor.test(BO_BV$BV_BO22, BO_BV$BV_BO23, method="pearson")

#combine plots using patchwork
patchwork1<-(AC|BB|BO|HR)
patchwork1

#save plots
ggsave("BV_samesite.png", device = "png", dpi = 1200)

```


#Figure S1: Probability density distribution of parental breeding values
```{r}
library(ggplot2)
library(patchwork)

#load data
AC_BV<-read.csv("AC_BV.csv")

#density Angelo Coast 2022
density_AC_1<-ggplot(AC_BV, aes(x=BV_AC22))+
  geom_density()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.key = element_rect(fill="white",color = NA), 
        axis.text.x = element_text(face="bold",size=12),
        axis.title.x = element_text(face="bold", size=12),
        axis.text.y = element_text(face="bold", size=12),
        axis.title.y = element_text(face="bold", size=14),
        legend.title=element_text(face="bold", size=14)) +
        labs(y= "Probability density", x="AC 2022")+ 
        scale_x_continuous(limits=c(0,6))
density_AC_1

#density Angelo Coast 2022
density_AC_2<-ggplot(AC_BV, aes(x=BV_AC23))+
  geom_density()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.key = element_rect(fill="white",color = NA), 
        axis.text.x = element_text(face="bold",size=12),
        axis.title.x = element_text(face="bold", size=12),
        axis.text.y = element_text(face="bold", size=12),
        axis.title.y = element_text(face="bold", size=14),
        legend.title=element_text(face="bold", size=14)) +
        labs(y= "Probability density", x="AC 2023")+ 
        scale_x_continuous(limits=c(0,6))
density_AC_2


#load data
BB_BV<-read.csv("BB_BV.csv")
# Fix common issues
if("BV_BB23" %in% colnames(BB_BV)) {
  BB_BV$BV_BB23 <- as.numeric(as.character(BB_BV$BV_BB23))
  print(summary(BB_BV$BV_BB23))
} else {
  stop("Column 'BV_BB23' not found in BB_BV dataset.")
}

#density Bodega Bay 2022
density_BB_1<-ggplot(BB_BV, aes(x=BV_BB22))+
  geom_density()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.key = element_rect(fill="white",color = NA), 
        axis.text.x = element_text(face="bold",size=12),
        axis.title.x = element_text(face="bold", size=12),
        axis.text.y = element_text(face="bold", size=12),
        axis.title.y = element_text(face="bold", size=14),
        legend.title=element_text(face="bold", size=14)) +
        labs(y= "Probability density", x="BB 2022")+ 
        scale_x_continuous(limits=c(0,6))
density_BB_1

#density Bodega Bay 2023
density_BB_2<-ggplot(BB_BV, aes(x=BV_BB23))+
  geom_density()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.key = element_rect(fill="white",color = NA), 
        axis.text.x = element_text(face="bold",size=12),
        axis.title.x = element_text(face="bold", size=12),
        axis.text.y = element_text(face="bold", size=12),
        axis.title.y = element_text(face="bold", size=14),
        legend.title=element_text(face="bold", size=14)) +
        labs(y= "Probability density", x="BB 2023")+ 
        scale_x_continuous(limits=c(0,35))
density_BB_2


#load data
BO_BV<-read.csv("BO_BV.csv")

#density Blue Oak 2022
density_BO_1<-ggplot(BO_BV, aes(x=BV_BO22))+
  geom_density()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.key = element_rect(fill="white",color = NA), 
        axis.text.x = element_text(face="bold",size=12),
        axis.title.x = element_text(face="bold", size=12),
        axis.text.y = element_text(face="bold", size=12),
        axis.title.y = element_text(face="bold", size=14),
        legend.title=element_text(face="bold", size=14)) +
        labs(y= "Probability density", x="BO 2022")+ 
        scale_x_continuous(limits=c(0,6))
density_BO_1

#density Blue Oak 2023
density_BO_2<-ggplot(BO_BV, aes(x=BV_BO23))+
  geom_density()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.key = element_rect(fill="white",color = NA), 
        axis.text.x = element_text(face="bold",size=12),
        axis.title.x = element_text(face="bold", size=12),
        axis.text.y = element_text(face="bold", size=12),
        axis.title.y = element_text(face="bold", size=14),
        legend.title=element_text(face="bold", size=14)) +
        labs(y= "Probability density", x="BO 2023")+ 
        scale_x_continuous(limits=c(0,6))
density_BO_2

#load data
HR_BV<-read.csv("HR_BV.csv")

#density Hastings Ranch 2022
density_HR_1<-ggplot(HR_BV, aes(x=BV_HR22))+
  geom_density()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.key = element_rect(fill="white",color = NA), 
        axis.text.x = element_text(face="bold",size=12),
        axis.title.x = element_text(face="bold", size=12),
        axis.text.y = element_text(face="bold", size=12),
        axis.title.y = element_text(face="bold", size=14),
        legend.title=element_text(face="bold", size=14)) +
        labs(y= "Probability density", x="HR 2022")+ 
        scale_x_continuous(limits=c(0,6))
density_HR_1

density_HR_2<-ggplot(HR_BV, aes(x=BV_HR22))+
  geom_density()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        legend.key = element_rect(fill="white",color = NA), 
        axis.text.x = element_text(face="bold",size=12),
        axis.title.x = element_text(face="bold", size=12),
        axis.text.y = element_text(face="bold", size=12),
        axis.title.y = element_text(face="bold", size=14),
        legend.title=element_text(face="bold", size=14)) +
        labs(y= "Probability density", x="HR 2023")+ 
        scale_x_continuous(limits=c(0,6))
density_HR_2


#combine plots using patchwork
patchwork<-(density_AC_1/density_AC_2|density_BB_1/density_BB_2|density_BO_1/density_BO_2|density_HR_1/density_HR_2)

patchwork

#code to save plot
ggsave('prob_density_BV.png', patchwork, device="png", dpi=1200)
```


##other figures

#Figure 1: Study site climate normals 
```{r}
options(repos = c(CRAN = "https://cran.rstudio.com/"))

library(tidyverse)
library(raster)
#library(rgdal) #old package no longer available
library(ggplot2)
library(sp)
library(rgeos)
library(gridExtra)
library(ggspatial)
library(sf)
# Install devtools if you don't have it already
#install.packages("devtools")

# Load the devtools package
library(devtools)

# Install the rnaturalearthhires package from GitHub
#devtools::install_github("ropensci/rnaturalearthhires")

library(rnaturalearth)

# Load the temperature raster
temprast <- raster("PRISM_tmean_30yr_normal.tif")

# Get the USA shapefile from rnaturalearth package
usa_sf <- ne_states(country = "united states of america", returnclass = "sf")

# Transform CRS to a recent format (e.g., EPSG:4326)
usa_sf <- st_transform(usa_sf, crs = 4326)

# Select the states of interest for the tristate area
tristate_sf <- usa_sf[usa_sf$name %in% ("California"),]

# Crop the raster to the tristate area
temprast_tristate <- crop(temprast, extent(tristate_sf))

# Convert raster to data frame
df <- as.data.frame(temprast_tristate, xy = TRUE)

# Data for the points and labels
labels_data <- data.frame(
  x = c(-123.65261752533642, -123.07109117331942, -121.73678882741571, -121.5627953728642),
  y = c(39.70791443219262,38.31820208912606, 37.38236329564739, 36.3793508087087),
  label = c("AC", "BB", "BO", "HR")
)
# To add a line break within the label, you can use "\n" in the label text:
labels_data$label[labels_data$label == "ML(home site)"] <- "ML\n(home site)"

plot1 <- ggplot() +
  geom_raster(data = df, aes(x = x, y = y, fill = PRISM_tmean_30yr_normal)) +
  scale_fill_gradientn(colours = hcl.colors(8, "YlOrRd", rev = TRUE), na.value = "white") +
  geom_sf(data = tristate_sf, fill = NA, color = "black") +
  geom_point(data = labels_data, aes(x = x, y = y), shape = 16, size = 3, color = "black") +  # White points
  geom_text(data = labels_data, aes(x = x, y = y, label = label),
            nudge_y = c(-0.06, 0.05, 0.05, 0.05),  # Adjust vertical position for each label
            vjust = c(-0.3, -0.35, -0.3, -0.3),   # Four values to match the four labels
            size = 5, color = "black") +  # Larger and white text labels
  labs(x = "Longitude", y = "Latitude", fill = expression(~Degree~C)) +
  coord_sf(crs = 4326) +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(colour = "black", size = 14),
        axis.ticks = element_line(colour = "black", linewidth = 0.5),
        axis.title = element_text(size = 16, face = "bold"),
        panel.border = element_rect(fill = NA, colour = "black"))

# Plot plot1
print(plot1)


# Load the precipitation raster
preciprast <- raster("PRISM_ppt_30yr_normal.tif")

# Crop the raster to the tristate area
preciprast_tristate <- crop(preciprast, extent(tristate_sf))

# Convert raster to data frame
df_precip <- as.data.frame(preciprast_tristate, xy = TRUE)

# Rename the columns
names(df_precip) <- c("x", "y", "precip")

# Plot the data
plot2 <- ggplot() +
  geom_raster(data = df_precip, aes(x = x, y = y, fill = precip), interpolate = TRUE) +
  scale_fill_gradientn(colours = hcl.colors(8, "Blues", rev = TRUE), na.value = "white") +
  geom_sf(data = tristate_sf, fill = NA, color = "black") +
  geom_point(data = labels_data, aes(x = x, y = y), shape = 16, size = 3, color = "black") +  # Black points
  geom_text(data = labels_data, aes(x = x, y = y, label = label),
            nudge_y = c(-0.06, 0.05, 0.05, 0.05),  # Adjust vertical position for each label
            vjust = c(-0.3, -0.35, -0.3, -0.3),   # Four values to match the four labels
            size = 5, color = "black") +  # Larger and black text labels
  labs(x = "Longitude", y = "Latitude", fill = "mm") +
  coord_sf(crs = 4326) +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_text(colour = "black", size = 14),
        axis.ticks = element_line(colour = "black", linewidth = 0.5),
        axis.title = element_text(size = 16, face = "bold"),
        panel.border = element_rect(fill = NA, colour = "black"))

# Combine plots into a single page using gridExtra
grid.arrange(plot1, plot2, nrow = 2)


# Save to a .png file
ggsave("combined_plots.png", arrangeGrob(plot1, plot2, nrow = 2), dpi = 1200, width = 9, height = 10)
```