---
title: "AC_Va_h2_R_2023"
author: "Helen Payne"
date: "2024-06-18"
output:
  pdf_document: default
  html_document: default
---

```{r}
#load packages
library(lme4)
library(tidyverse)
```

###########**2023**##########

Read in the data:
```{r}
AC_23 <- read_csv(here::here("data_sheets", "compiled_sheets", "AC_mastersheet_Fitness-mains_2023.csv"))

AC_23_fit_G2 <- AC_23 %>% 
  filter(Gen == "G2")

```

```{r}
# Create the mixed model for corolla area

corolla_model <- lmer(corolla_diam_mm_SEG ~ (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(corolla_model)

# Q-Q plot for normality
qqnorm(residuals) #looks good


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal

#####
#Calculate the group means
group_means <- AC_23_fit_G2 %>%
  group_by(Transect) %>%
  summarise(mean_corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE))

#Mean center the variable by Transect
AC_23_fit_G2 <- AC_23_fit_G2 %>%
  left_join(group_means, by = "Transect") %>%
  mutate(corolla_diam_mm_SEG_centered = corolla_diam_mm_SEG - mean_corolla_diam_mm_SEG) %>%
  select(-mean_corolla_diam_mm_SEG)  # Optional: Remove the mean_corolla_diam column
#####

#Fit the model using the mean-centered variable
corolla_model_3 <- lmer((corolla_diam_mm_SEG_centered) ~ Transect + (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(corolla_model_3)

# Q-Q plot for normality
qqnorm(residuals) #looks good


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal

```

```{r}

# Create the mixed model for skeleton weight, with skeleton weight log transformed
skel_model <- lmer(log(skel_dryweight_mg_SEG) ~ (1 |Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(skel_model)

# Q-Q plot for normality
qqnorm(residuals) #looks good


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal


# Create the mixed model for skeleton weight, with skeleton weight log transformed
skel_model_2 <- lmer(log(skel_dryweight_mg_SEG) ~ Transect + (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(skel_model_2)

# Q-Q plot for normality
qqnorm(residuals) #looks good


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal


#####
#Calculate the group means
group_means <- AC_23_fit_G2 %>%
  group_by(Transect) %>%
  summarise(mean_skel_dryweight_mg_SEG = mean(skel_dryweight_mg_SEG, na.rm = TRUE))

#Mean center the variable by Transect
AC_23_fit_G2 <- AC_23_fit_G2 %>%
  left_join(group_means, by = "Transect") %>%
  mutate(skel_dryweight_mg_SEG_centered = skel_dryweight_mg_SEG - mean_skel_dryweight_mg_SEG) %>%
  select(-mean_skel_dryweight_mg_SEG)  # Optional: Remove the mean_corolla_diam column
#####

#Fit the model using the mean-centered variable
skel_model_3 <- lmer((skel_dryweight_mg_SEG_centered) ~ Transect + (1 | Donor:  Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(skel_model_3)

# Q-Q plot for normality
qqnorm(residuals) #looks good


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal

```


```{r}
# Create the mixed model for flowering duration
fl_duration_model <- lmer(fl_duration ~ (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Check if the model is singular
isSingular(fl_duration_model) #TRUE, likely due to over-fitting, will not include
```
```{r}

# Compare models using AIC, BIC, and log-likelihood
skel_model_comparison <- data.frame(
  Model = c("skel_model", "skel_model_2", "skel_model_3"),
  AIC = c(AIC(skel_model), AIC(skel_model_2), AIC(skel_model_3)),
  BIC = c(BIC(skel_model), BIC(skel_model_2), BIC(skel_model_3)),
  LogLikelihood = c(logLik(skel_model), logLik(skel_model_2), logLik(skel_model_3))
)

# Print model comparison
print(skel_model_comparison)

#model 2 is the best

```

```{r}
# Create the mixed model for estimated fecundity, sqrt transforming estimated fecundity
est_fecundity_model <- lmer((est_fecundity) ~ (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(est_fecundity_model)

# Q-Q plot for normality
qqnorm(residuals) #good enough


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal-ish


# Create the mixed model for estimated fecundity, sqrt transforming estimated fecundity
est_fecundity_model_2 <- lmer((est_fecundity) ~ Transect + (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(est_fecundity_model_2)

# Q-Q plot for normality
qqnorm(residuals) #good enough


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal-ish


#####
#Calculate the group means
group_means <- AC_23_fit_G2 %>%
  group_by(Transect) %>%
  summarise(mean_est_fecundity = mean(est_fecundity, na.rm = TRUE))

#Mean center the variable by Transect
AC_23_fit_G2 <- AC_23_fit_G2 %>%
  left_join(group_means, by = "Transect") %>%
  mutate(est_fecundity_centered = est_fecundity - mean_est_fecundity) %>%
  select(-mean_est_fecundity)  # Optional: Remove the mean_corolla_diam column
#####

#Fit the model using the mean-centered variable
est_fecundity_model_3 <- lmer((est_fecundity_centered) ~ Transect + (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(est_fecundity_model_3)

# Q-Q plot for normality
qqnorm(residuals) #good enough


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal-ish

```

```{r}
# Compare models using AIC, BIC, and log-likelihood
est_fecundity_model_comparison <- data.frame(
  Model = c("est_fecundity_model", "est_fecundity_model_2", "est_fecundity_model_3"),
  AIC = c(AIC(est_fecundity_model), AIC(est_fecundity_model_2), AIC(est_fecundity_model_3)),
  BIC = c(BIC(est_fecundity_model), BIC(est_fecundity_model_2), BIC(est_fecundity_model_3)),
  LogLikelihood = c(logLik(est_fecundity_model), logLik(est_fecundity_model_2), logLik(est_fecundity_model_3))
)

# Print model comparison
print(est_fecundity_model_comparison)

#model 3 is the best
```


```{r}
# Create the mixed model for mean seed mass, log transformed mean seed mass
msm_model <- lmer(log(msm_all) ~ (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(msm_model)

# Q-Q plot for normality
qqnorm(residuals) #good enough


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal-ish

# Create the mixed model for mean seed mass, log transformed mean seed mass
msm_model_2 <- lmer(log(msm_all) ~ Transect + (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(msm_model)

# Q-Q plot for normality
qqnorm(residuals) #good enough

# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal-ish


#####
#Calculate the group means
group_means <- AC_23_fit_G2 %>%
  group_by(Transect) %>%
  summarise(mean_msm = mean(msm_all, na.rm = TRUE))

#Mean center the variable by Transect
AC_23_fit_G2 <- AC_23_fit_G2 %>%
  left_join(group_means, by = "Transect") %>%
  mutate(msm_centered = msm_all - mean_msm) %>%
  select(-mean_msm)  # Optional: Remove the mean_corolla_diam column
#####

#Fit the model using the mean-centered variable
msm_model_3 <- lmer((msm_centered) ~ Transect + (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(msm_model_3)

# Q-Q plot for normality
qqnorm(residuals) #good enough


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal-ish

```

```{r}

# Compare models using AIC, BIC, and log-likelihood
msm_model_comparison <- data.frame(
  Model = c("msm_model", "msm_model_2", "msm_model_3"),
  AIC = c(AIC(msm_model), AIC(msm_model_2), AIC(msm_model_3)),
  BIC = c(BIC(msm_model), BIC(msm_model_2), BIC(msm_model_3)),
  LogLikelihood = c(logLik(msm_model), logLik(msm_model_2), logLik(msm_model_3))
)

# Print model comparison
print(msm_model_comparison)

#model 1 is the best

```

```{r}
# Create the mixed model for SLA
SLA_model <- lmer(log(SLA_SEG) ~ (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(SLA_model)

# Q-Q plot for normality
qqnorm(residuals) #okay.. 


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #definitely a few outliers, but maybe okay?


##adding in transect##
# Create the mixed model for SLA
SLA_model_2 <- lmer(log(SLA_SEG) ~ Transect + (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(SLA_model_2)

# Q-Q plot for normality
qqnorm(residuals) #okay.. 


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #definitely a few outliers, but maybe okay?

#####
#Calculate the group means
group_means <- AC_23_fit_G2 %>%
  group_by(Transect) %>%
  summarise(mean_SLA_SEG = mean(SLA_SEG, na.rm = TRUE))

#Mean center the variable by Transect
AC_23_fit_G2 <- AC_23_fit_G2 %>%
  left_join(group_means, by = "Transect") %>%
  mutate(SLA_SEG_centered = SLA_SEG - mean_SLA_SEG) %>%
  select(-mean_SLA_SEG)  # Optional: Remove the mean_corolla_diam column
#####

#Fit the model using the mean-centered variable
SLA_model_3 <- lmer((SLA_SEG_centered) ~ Transect + (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(SLA_model_3)

# Q-Q plot for normality
qqnorm(residuals) #good enough


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal-ish

```

```{r}

# Compare models using AIC, BIC, and log-likelihood
SLA_model_comparison <- data.frame(
  Model = c("SLA_model", "SLA_model_2", "SLA_model_3"),
  AIC = c(AIC(SLA_model), AIC(SLA_model_2), AIC(SLA_model_3)),
  BIC = c(BIC(SLA_model), BIC(SLA_model_2), BIC(SLA_model_3)),
  LogLikelihood = c(logLik(SLA_model), logLik(SLA_model_2), logLik(SLA_model_3))
)

# Print model comparison
print(SLA_model_comparison)

#model 2 is the best

```


```{r}
# Create the mixed model for mean seed mass, log transformed mean seed mass
LMA_model <- lmer(LMA_SEG ~ (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Check if the model is singular
isSingular(LMA_model) #TRUE, likely due to over-fitting, will not include
```

```{r}
# Create the mixed model for d13C, log transformed mean seed mass
d13C_model <- lmer(d13C_SEG ~ (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(d13C_model)

# Q-Q plot for normality
qqnorm(residuals) #good enough


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal-ish

# Create the mixed model for d13C, log transformed mean seed mass
d13C_model_2 <- lmer(d13C_SEG ~ Transect + (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(d13C_model_2)

# Q-Q plot for normality
qqnorm(residuals) #good enough


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal-ish

#####
#Calculate the group means
group_means <- AC_23_fit_G2 %>%
  group_by(Transect) %>%
  summarise(mean_d13C_SEG = mean(d13C_SEG, na.rm = TRUE))

#Mean center the variable by Transect
AC_23_fit_G2 <- AC_23_fit_G2 %>%
  left_join(group_means, by = "Transect") %>%
  mutate(d13C_SEG_centered = d13C_SEG - mean_d13C_SEG) %>%
  select(-mean_d13C_SEG)  # Optional: Remove the mean_corolla_diam column
#####

#Fit the model using the mean-centered variable
d13C_model_3 <- lmer((d13C_SEG_centered) ~ Transect + (1 | Donor: Recipient) + (1 | Donor), data = AC_23_fit_G2)

# Extract residuals from the model
residuals <- resid(d13C_model_3)

# Q-Q plot for normality
qqnorm(residuals) #good enough


# Histogram for normality
hist(residuals, breaks = 20, main = "Histogram of Residuals", xlab = "Residuals") #normal-ish

```

```{r}

# Compare models using AIC, BIC, and log-likelihood
d13C_model_comparison <- data.frame(
  Model = c("d13C_model", "d13C_model_2", "d13C_model_3"),
  AIC = c(AIC(d13C_model), AIC(d13C_model_2), AIC(d13C_model_3)),
  BIC = c(BIC(d13C_model), BIC(d13C_model_2), BIC(d13C_model_3)),
  LogLikelihood = c(logLik(d13C_model), logLik(d13C_model_2), logLik(d13C_model_3))
)

# Print model comparison
print(d13C_model_comparison)

#model 3 is the best

```

```{r}
# Define the function to extract variance components and calculate required values
calculate_variances <- function(model, trait_name) {
  var_components <- as.data.frame(VarCorr(model))
  
  # Check if all required components are present
  if (all(c("Recipient", "Donor", "Residual") %in% var_components$grp)) {
    Va_mat <- var_components$vcov[var_components$grp == "Recipient"]
    Va_pat <- var_components$vcov[var_components$grp == "Donor"]
    res_var <- var_components$vcov[var_components$grp == "Residual"]
    
    # Calculate the standard deviation
    Vp <- Va_mat + Va_pat + res_var
    Va_sd_mat <- sqrt(Va_mat)
    Va_sd_pat <- sqrt(Va_pat)
    Vp_sd <- sqrt(Vp)
    
    # Calculate narrow-sense heritability
    h2 <- (Va_pat) / Vp  # assumed calculation
    
    # Create the dataframe and add the traits column
    df <- data.frame(traits = trait_name, Va_mat, Va_sd_mat, Va_pat, Va_sd_pat, Vp, Vp_sd, h2)
  } else {
    # Return an empty dataframe if any component is missing
    df <- data.frame(traits = trait_name, Va_mat = NA, Va_sd_mat = NA, Va_pat = NA, Va_sd_pat = NA, Vp = NA, Vp_sd = NA, h2 = NA)
  }
  
  return(df)
}

# List of models and corresponding trait names
models <- list(skel_model_2, d13C_model_3, est_fecundity_model_3, msm_model, SLA_model_2)
trait_names <- c("skel_biomass_mg", "delta_C_13", "estimated_fecundity", "mean_seed_mass", "SLA")

# Initialize an empty dataframe to store results
variance_AC_2023 <- data.frame()

# Loop over each model and trait name, calculate variances, and combine results
for (i in seq_along(models)) {
  variances <- calculate_variances(models[[i]], trait_names[i])
  variance_AC_2023 <- rbind(variance_AC_2023, variances)
}

```


```{r}
#Save the csv file if you want
write_csv(x = variance_AC_2023, here::here("data_sheets", "compiled_sheets", "AC_Va_h2_R_2023.csv"))

```

