---
title: "Sewn Seed Mass"
author: "Helen Payne"
date: "2025-02-11"
output: html_document
---

###AC###

Load in libraries and the datasets, plus a bit of tidying
```{r}
# Load the lme4 package
library(lme4)
library(tidyverse)


### Load and preprocess data
## Data for fitness plants only
# Read the CSV file and create 'sample_ID' column
AC_fit <- read_csv(here::here("data_sheets", "compiled_sheets", "AC_22_23_fit.csv")) %>%
  rename_at(vars(48), ~"surv_to_fruitpod") %>% #rename this column which was miss spelled
  mutate(
    # Construct sample_ID conditionally
    sample_ID = case_when(
      is.na(SegPos) ~ paste(Year, Recipient, Gen, str_pad(Transect, width = 3, pad = "0"), Plant_ID, sep = "-"),
      TRUE ~ paste(Year, Recipient, Gen, str_pad(Transect, width = 3, pad = "0"), SegPos, Plant_ID, sep = "-")
    ),
    # Replace leading underscores in sample_ID with hyphens
    sample_ID = str_replace(sample_ID, "^([^_]*)_", "\\1-")
  )

# Read in data from non-fitness plants- this is to get survival data from
AC_22_23_full <- read_csv(here::here("data_sheets", "compiled_sheets", "AC_22_23_full.csv"))

#create the variable "prop_surv_to_flower"
AC_22_23_full <- AC_22_23_full %>%
  group_by(Year, Gen, Transect, Sequence, Donor, Recipient, SegPos) %>%
  mutate(prop_surv_to_flower = mean(surv_to_flower, na.rm = TRUE)) %>%
  ungroup()  # Remove grouping

#select for certain columns
AC_prop_sample <- AC_22_23_full %>%
  dplyr::select(c(Year, Gen, Transect, Sequence, Donor, Recipient, SegPos, prop_surv_to_flower))  %>%
    distinct()

#add "prop_surv_to_flower" based on the columns listed
AC_fit <- AC_fit %>%
  left_join(AC_prop_sample %>% dplyr::select(Year, Gen, Transect, Sequence, Donor, Recipient, SegPos, prop_surv_to_flower),
            by = c("Year", "Gen", "Transect", "Sequence", "Donor", "Recipient", "SegPos"))

# Create the new column for "est_fitness" and rename "prop_surv_to_flower" to "survival"
AC_fit <- AC_fit %>%
  mutate(est_fitness = prop_surv_to_flower * est_fecundity) %>%
  mutate(est_fitness = replace_na(est_fitness, 0)) %>%
  rename(survival = prop_surv_to_flower)

#isolate AC 2022
AC_fit_22 <- AC_fit %>%
  filter(Year == "2022")

#isolate AC 2023 G1
AC_fit_23_G1 <- AC_fit %>%
  filter(Year == "2023", Gen == "G1")

#isolate AC 2023 G2
AC_fit_23_G2 <- AC_fit %>%
  filter(Year == "2023", Gen == "G2")

#isolate all G1 together
AC_fit_G1 <- AC_fit %>%
  filter(Gen == "G1")

#isolate by year
AC_fit_23 <- AC_fit %>%
  filter(Year == "2023")

```


```{r}

AC_fit_22_unique <- AC_fit_22 %>%
  group_by(Donor, Recipient) %>%
  summarise(g0_msm = mean(msm_all, na.rm = TRUE), .groups = "drop")

AC_fit_23_G2 <- AC_fit_23_G2 %>%
  left_join(AC_fit_22_unique, by = c("Donor", "Recipient"))

```

Average based on paternal donor mean trait values
```{r}
##Obtain paternal genotypic values - this is what we are interested in
# Aggregate data by donor
AC_mean_donor_traits_22 <- AC_fit_22%>%
  group_by(Donor) %>%             # Group by donor
  summarise(
    closed_fruits = mean(closed_fruits, na.rm = TRUE),
    total_fruits = mean(total_fruits, na.rm = TRUE),
    filled_seeds = mean(filled_seeds, na.rm = TRUE),
    mean_seeds_per_fruit = mean(mean_seeds_per_fruit, na.rm = TRUE),
    fl_duration = mean(fl_duration, na.rm = TRUE),
    skel_dryweight_mg = mean(skel_dryweight_mg, na.rm = TRUE),
    msm_all = mean(msm_all, na.rm = TRUE),
    corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE),
    SLA_SEG = mean(SLA_SEG, na.rm = TRUE),
    d13C_SEG = mean(d13C_SEG, na.rm = TRUE),
    est_fecundity = mean(est_fecundity, na.rm = TRUE),
    survival = mean(survival, na.rm = TRUE),
    est_fitness = mean(est_fitness, na.rm = TRUE),
        count = n() 
  )

AC_mean_donor_traits_23_G1 <- AC_fit_23_G1%>%
  group_by(Donor) %>%             # Group by donor
  summarise(
    closed_fruits = mean(closed_fruits, na.rm = TRUE),
    total_fruits = mean(total_fruits, na.rm = TRUE),
    filled_seeds = mean(filled_seeds, na.rm = TRUE),
    mean_seeds_per_fruit = mean(mean_seeds_per_fruit, na.rm = TRUE),
    fl_duration = mean(fl_duration, na.rm = TRUE),
    skel_dryweight_mg = mean(skel_dryweight_mg, na.rm = TRUE),
    msm_all = mean(msm_all, na.rm = TRUE),
    corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE),
    SLA_SEG = mean(SLA_SEG, na.rm = TRUE),
    d13C_SEG = mean(d13C_SEG, na.rm = TRUE),
    est_fecundity = mean(est_fecundity, na.rm = TRUE),
    survival = mean(survival, na.rm = TRUE),
    est_fitness = mean(est_fitness, na.rm = TRUE),
        count = n() 
  )

AC_mean_donor_traits_23_G2 <- AC_fit_23_G2%>%
  group_by(Donor) %>%             # Group by donor
  summarise(
    closed_fruits = mean(closed_fruits, na.rm = TRUE),
    total_fruits = mean(total_fruits, na.rm = TRUE),
    filled_seeds = mean(filled_seeds, na.rm = TRUE),
    mean_seeds_per_fruit = mean(mean_seeds_per_fruit, na.rm = TRUE),
    fl_duration = mean(fl_duration, na.rm = TRUE),
    skel_dryweight_mg = mean(skel_dryweight_mg, na.rm = TRUE),
    msm_all = mean(msm_all, na.rm = TRUE),
    corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE),
    SLA_SEG = mean(SLA_SEG, na.rm = TRUE),
    d13C_SEG = mean(d13C_SEG, na.rm = TRUE),
    est_fecundity = mean(est_fecundity, na.rm = TRUE),
    survival = mean(survival, na.rm = TRUE),
    est_fitness = mean(est_fitness, na.rm = TRUE),
    g0_msm = mean(g0_msm, na.rm = TRUE),
        count = n() 
  )
```




```{r}

correlation <- cor(AC_mean_donor_traits_23_G2$g0_msm, AC_mean_donor_traits_23_G2$msm_all, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

correlation <- cor(AC_mean_donor_traits_23_G2$g0_msm, AC_mean_donor_traits_23_G2$survival, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

correlation <- cor(AC_mean_donor_traits_23_G2$g0_msm, AC_mean_donor_traits_23_G2$est_fecundity, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

correlation <- cor(AC_mean_donor_traits_23_G2$g0_msm, AC_mean_donor_traits_23_G2$est_fitness, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

```

###BB###


```{r}
### Load and preprocess data
## Data for fitness plants only
# Read the CSV file and create 'sample_ID' column
BB_fit <- read_csv(here::here("data_sheets", "compiled_sheets", "BB_22_23_fit.csv")) %>%
  mutate(
    # Construct sample_ID conditionally
    sample_ID = case_when(
      is.na(SegPos) ~ paste(Year, Recipient, Gen, str_pad(Location, width = 3, pad = "0"), Plant_ID, sep = "-"),
      TRUE ~ paste(Year, Recipient, Gen, str_pad(Location, width = 3, pad = "0"), SegPos, Plant_ID, sep = "-")
    ),
    # Replace leading underscores in sample_ID with hyphens
    sample_ID = str_replace(sample_ID, "^([^_]*)_", "\\1-")
  )

# Read in data from non-fitness plants- this is to get survival data from
BB_22_23_full <- read_csv(here::here("data_sheets", "compiled_sheets", "BB_22_23_full.csv"))

#create the variable "prop_surv_to_flower"
BB_22_23_full <- BB_22_23_full %>%
  group_by(Year, Gen, Location, Sequence, Donor, Recipient, SegPos) %>%
  mutate(prop_surv_to_flower = mean(surv_to_flower, na.rm = TRUE)) %>%
  ungroup()  # Remove grouping

#select for certain columns
BB_prop_sample <- BB_22_23_full %>%
  dplyr::select(c(Year, Gen, Location, Sequence, Donor, Recipient, SegPos, prop_surv_to_flower))  %>%
    distinct()

#add "prop_surv_to_flower" based on the columns listed
BB_fit <- BB_fit %>%
  left_join(BB_prop_sample %>% dplyr::select(Year, Gen, Location, Sequence, Donor, Recipient, SegPos, prop_surv_to_flower),
            by = c("Year", "Gen", "Location", "Sequence", "Donor", "Recipient", "SegPos"))

# Create the new column for "est_fitness" and rename "prop_surv_to_flower" to "survival"
BB_fit <- BB_fit %>%
  mutate(est_fitness = prop_surv_to_flower * est_fecundity) %>%
  mutate(est_fitness = replace_na(est_fitness, 0)) %>%
  rename(survival = prop_surv_to_flower)

#isolate BB 2022
BB_fit_22 <- BB_fit %>%
  filter(Year == "2022")

#isolate BB 2023 G1
BB_fit_23_G1 <- BB_fit %>%
  filter(Year == "2023", Gen == "G1")

#isolate BB 2023 G2
BB_fit_23_G2 <- BB_fit %>%
  filter(Year == "2023", Gen == "G2")

#isolate all G1 together
BB_fit_G1 <- BB_fit %>%
  filter(Gen == "G1")

#isolate by year
BB_fit_23 <- BB_fit %>%
  filter(Year == "2023")

```
```{r}

BB_fit_22_unique <- BB_fit_22 %>%
  group_by(Donor, Recipient) %>%
  summarise(g0_msm = mean(msm_all, na.rm = TRUE), .groups = "drop")

BB_fit_23_G2 <- BB_fit_23_G2 %>%
  left_join(BB_fit_22_unique, by = c("Donor", "Recipient"))

```



Average based on paternal donor mean trait values
```{r}
##Obtain paternal genotypic values - this is what we are interested in
# Aggregate data by donor
BB_mean_donor_traits_22 <- BB_fit_22%>%
  group_by(Donor) %>%             # Group by donor
  summarise(
    closed_fruits = mean(closed_fruits, na.rm = TRUE),
    total_fruits = mean(total_fruits, na.rm = TRUE),
    filled_seeds = mean(filled_seeds, na.rm = TRUE),
    mean_seeds_per_fruit = mean(mean_seeds_per_fruit, na.rm = TRUE),
    fl_duration = mean(fl_duration, na.rm = TRUE),
    skel_dryweight_mg = mean(skel_dryweight_mg, na.rm = TRUE),
    msm_all = mean(msm_all, na.rm = TRUE),
    corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE),
    SLA_SEG = mean(SLA_SEG, na.rm = TRUE),
    d13C_SEG = mean(d13C_SEG, na.rm = TRUE),
    est_fecundity = mean(est_fecundity, na.rm = TRUE),
    survival = mean(survival, na.rm = TRUE),
    est_fitness = mean(est_fitness, na.rm = TRUE),
        count = n() 
  )

BB_mean_donor_traits_23_G1 <- BB_fit_23_G1%>%
  group_by(Donor) %>%             # Group by donor
  summarise(
    closed_fruits = mean(closed_fruits, na.rm = TRUE),
    total_fruits = mean(total_fruits, na.rm = TRUE),
    filled_seeds = mean(filled_seeds, na.rm = TRUE),
    mean_seeds_per_fruit = mean(mean_seeds_per_fruit, na.rm = TRUE),
    fl_duration = mean(fl_duration, na.rm = TRUE),
    skel_dryweight_mg = mean(skel_dryweight_mg, na.rm = TRUE),
    msm_all = mean(msm_all, na.rm = TRUE),
    corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE),
    SLA_SEG = mean(SLA_SEG, na.rm = TRUE),
    d13C_SEG = mean(d13C_SEG, na.rm = TRUE),
    est_fecundity = mean(est_fecundity, na.rm = TRUE),
    survival = mean(survival, na.rm = TRUE),
    est_fitness = mean(est_fitness, na.rm = TRUE),
        count = n() 
  )

BB_mean_donor_traits_23_G2 <- BB_fit_23_G2%>%
  group_by(Donor) %>%             # Group by donor
  summarise(
    closed_fruits = mean(closed_fruits, na.rm = TRUE),
    total_fruits = mean(total_fruits, na.rm = TRUE),
    filled_seeds = mean(filled_seeds, na.rm = TRUE),
    mean_seeds_per_fruit = mean(mean_seeds_per_fruit, na.rm = TRUE),
    fl_duration = mean(fl_duration, na.rm = TRUE),
    skel_dryweight_mg = mean(skel_dryweight_mg, na.rm = TRUE),
    msm_all = mean(msm_all, na.rm = TRUE),
    corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE),
    SLA_SEG = mean(SLA_SEG, na.rm = TRUE),
    d13C_SEG = mean(d13C_SEG, na.rm = TRUE),
    est_fecundity = mean(est_fecundity, na.rm = TRUE),
    survival = mean(survival, na.rm = TRUE),
    est_fitness = mean(est_fitness, na.rm = TRUE),
    g0_msm = mean(g0_msm, na.rm = TRUE),
        count = n() 
  )
```

```{r}

correlation <- cor(BB_mean_donor_traits_23_G2$g0_msm, BB_mean_donor_traits_23_G2$msm_all, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

correlation <- cor(BB_mean_donor_traits_23_G2$g0_msm, BB_mean_donor_traits_23_G2$survival, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

correlation <- cor(BB_mean_donor_traits_23_G2$g0_msm, BB_mean_donor_traits_23_G2$est_fecundity, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

correlation <- cor(BB_mean_donor_traits_23_G2$g0_msm, BB_mean_donor_traits_23_G2$est_fitness, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

```



###BO###

```{r}
# Load the lme4 package
library(lme4)
library(dplyr)
library(tidyverse)


### Load and preprocess data
## Data for fitness plants only
# Read the CSV file and create 'sample_ID' column
BO_fit <- read_csv(here::here("data_sheets", "compiled_sheets", "BO_22_23_fit.csv")) %>%
  rename_at(vars(49), ~"surv_to_fruitpod") %>% #rename this column which was miss spelled
  mutate(
    # Construct sample_ID conditionally
    sample_ID = case_when(
      is.na(SegPos) ~ paste(Year, Recipient, Gen, str_pad(Transect, width = 3, pad = "0"), Plant_ID, sep = "-"),
      TRUE ~ paste(Year, Recipient, Gen, str_pad(Transect, width = 3, pad = "0"), SegPos, Plant_ID, sep = "-")
    ),
    # Replace leading underscores in sample_ID with hyphens
    sample_ID = str_replace(sample_ID, "^([^_]*)_", "\\1-")
  )

# Read in data from non-fitness plants- this is to get survival data from
BO_22_23_full <- read_csv(here::here("data_sheets", "compiled_sheets", "BO_22_23_full.csv"))

#create the variable "prop_surv_to_flower"
BO_22_23_full <- BO_22_23_full %>%
  group_by(Year, Gen, Transect, Sequence, Donor, Recipient, SegPos) %>%
  mutate(prop_surv_to_flower = mean(surv_to_flower, na.rm = TRUE)) %>%
  ungroup()  # Remove grouping

#select for certain columns
BO_prop_sample <- BO_22_23_full %>%
  dplyr::select(c(Year, Gen, Transect, Sequence, Donor, Recipient, SegPos, prop_surv_to_flower))  %>%
    distinct()

#add "prop_surv_to_flower" based on the columns listed
BO_fit <- BO_fit %>%
  left_join(BO_prop_sample %>% dplyr::select(Year, Gen, Transect, Sequence, Donor, Recipient, SegPos, prop_surv_to_flower),
            by = c("Year", "Gen", "Transect", "Sequence", "Donor", "Recipient", "SegPos"))

# Create the new column for "est_fitness" and rename "prop_surv_to_flower" to "survival"
BO_fit <- BO_fit %>%
  mutate(est_fitness = prop_surv_to_flower * est_fecundity) %>%
  mutate(est_fitness = replace_na(est_fitness, 0)) %>%
  rename(survival = prop_surv_to_flower)

#isolate BO 2022
BO_fit_22 <- BO_fit %>%
  filter(Year == "2022")

#isolate BO 2023 G1
BO_fit_23_G1 <- BO_fit %>%
  filter(Year == "2023", Gen == "G1")

#isolate BO 2023 G2
BO_fit_23_G2 <- BO_fit %>%
  filter(Year == "2023", Gen == "G2")

#isolate all G1 together
BO_fit_G1 <- BO_fit %>%
  filter(Gen == "G1")

#isolate by year
BO_fit_23 <- BO_fit %>%
  filter(Year == "2023")

```

```{r}

BO_fit_22_unique <- BO_fit_22 %>%
  group_by(Donor, Recipient) %>%
  summarise(g0_msm = mean(msm_all, na.rm = TRUE), .groups = "drop")

BO_fit_23_G2 <- BO_fit_23_G2 %>%
  left_join(BO_fit_22_unique, by = c("Donor", "Recipient"))

```


Average based on paternal donor mean trait values
```{r}
##Obtain paternal genotypic values - this is what we are interested in
# Aggregate data by donor
BO_mean_donor_traits_22 <- BO_fit_22%>%
  group_by(Donor) %>%             # Group by donor
  summarise(
    closed_fruits = mean(closed_fruits, na.rm = TRUE),
    total_fruits = mean(total_fruits, na.rm = TRUE),
    filled_seeds = mean(filled_seeds, na.rm = TRUE),
    mean_seeds_per_fruit = mean(mean_seeds_per_fruit, na.rm = TRUE),
    fl_duration = mean(fl_duration, na.rm = TRUE),
    skel_dryweight_mg = mean(skel_dryweight_mg, na.rm = TRUE),
    msm_all = mean(msm_all, na.rm = TRUE),
    corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE),
    SLA_SEG = mean(SLA_SEG, na.rm = TRUE),
    d13C_SEG = mean(d13C_SEG, na.rm = TRUE),
    est_fecundity = mean(est_fecundity, na.rm = TRUE),
    survival = mean(survival, na.rm = TRUE),
    est_fitness = mean(est_fitness, na.rm = TRUE),
        count = n() 
  )

BO_mean_donor_traits_23_G1 <- BO_fit_23_G1%>%
  group_by(Donor) %>%             # Group by donor
  summarise(
    closed_fruits = mean(closed_fruits, na.rm = TRUE),
    total_fruits = mean(total_fruits, na.rm = TRUE),
    filled_seeds = mean(filled_seeds, na.rm = TRUE),
    mean_seeds_per_fruit = mean(mean_seeds_per_fruit, na.rm = TRUE),
    fl_duration = mean(fl_duration, na.rm = TRUE),
    skel_dryweight_mg = mean(skel_dryweight_mg, na.rm = TRUE),
    msm_all = mean(msm_all, na.rm = TRUE),
    corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE),
    SLA_SEG = mean(SLA_SEG, na.rm = TRUE),
    d13C_SEG = mean(d13C_SEG, na.rm = TRUE),
    est_fecundity = mean(est_fecundity, na.rm = TRUE),
    survival = mean(survival, na.rm = TRUE),
    est_fitness = mean(est_fitness, na.rm = TRUE),
        count = n() 
  )

BO_mean_donor_traits_23_G2 <- BO_fit_23_G2%>%
  group_by(Donor) %>%             # Group by donor
  summarise(
    closed_fruits = mean(closed_fruits, na.rm = TRUE),
    total_fruits = mean(total_fruits, na.rm = TRUE),
    filled_seeds = mean(filled_seeds, na.rm = TRUE),
    mean_seeds_per_fruit = mean(mean_seeds_per_fruit, na.rm = TRUE),
    fl_duration = mean(fl_duration, na.rm = TRUE),
    skel_dryweight_mg = mean(skel_dryweight_mg, na.rm = TRUE),
    msm_all = mean(msm_all, na.rm = TRUE),
    corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE),
    SLA_SEG = mean(SLA_SEG, na.rm = TRUE),
    d13C_SEG = mean(d13C_SEG, na.rm = TRUE),
    est_fecundity = mean(est_fecundity, na.rm = TRUE),
    survival = mean(survival, na.rm = TRUE),
    est_fitness = mean(est_fitness, na.rm = TRUE),
    g0_msm = mean(g0_msm, na.rm = TRUE),
        count = n() 
  )
```

```{r}

correlation <- cor(BO_mean_donor_traits_23_G2$g0_msm, BO_mean_donor_traits_23_G2$msm_all, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

correlation <- cor(BO_mean_donor_traits_23_G2$g0_msm, BO_mean_donor_traits_23_G2$survival, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

correlation <- cor(BO_mean_donor_traits_23_G2$g0_msm, BO_mean_donor_traits_23_G2$est_fecundity, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

correlation <- cor(BO_mean_donor_traits_23_G2$g0_msm, BO_mean_donor_traits_23_G2$est_fitness, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

```


###HR###
```{r}
# Load the lme4 pHRkage
library(lme4)
library(dplyr)
library(tidyverse)


### Load and preprocess data
## Data for fitness plants only
# Read the CSV file and create 'sample_ID' column
HR_fit <- read_csv(here::here("data_sheets", "compiled_sheets", "HR_22_23_fit.csv")) %>%
  mutate(
    # Construct sample_ID conditionally
    sample_ID = case_when(
      is.na(SegPos) ~ paste(Year, Recipient, Gen, str_pad(Transect, width = 3, pad = "0"), Plant_ID, sep = "-"),
      TRUE ~ paste(Year, Recipient, Gen, str_pad(Transect, width = 3, pad = "0"), SegPos, Plant_ID, sep = "-")
    ),
    # Replace leading underscores in sample_ID with hyphens
    sample_ID = str_replace(sample_ID, "^([^_]*)_", "\\1-")
  )

# Read in data from non-fitness plants- this is to get survival data from
HR_22_23_full <- read_csv(here::here("data_sheets", "compiled_sheets", "HR_22_23_full.csv"))

#create the variable "prop_surv_to_flower"
HR_22_23_full <- HR_22_23_full %>%
  group_by(Year, Gen, Transect, Sequence, Donor, Recipient, SegPos) %>%
  mutate(prop_surv_to_flower = mean(surv_to_flower, na.rm = TRUE)) %>%
  ungroup()  # Remove grouping

#select for certain columns
HR_prop_sample <- HR_22_23_full %>%
  dplyr::select(c(Year, Gen, Transect, Sequence, Donor, Recipient, SegPos, prop_surv_to_flower))  %>%
    distinct()

#add "prop_surv_to_flower" based on the columns listed
HR_fit <- HR_fit %>%
  left_join(HR_prop_sample %>% dplyr::select(Year, Gen, Transect, Sequence, Donor, Recipient, SegPos, prop_surv_to_flower),
            by = c("Year", "Gen", "Transect", "Sequence", "Donor", "Recipient", "SegPos"))

# Create the new column for "est_fitness" and rename "prop_surv_to_flower" to "survival"
HR_fit <- HR_fit %>%
  mutate(est_fitness = prop_surv_to_flower * est_fecundity) %>%
  mutate(est_fitness = replace_na(est_fitness, 0)) %>%
  rename(survival = prop_surv_to_flower)

#isolate HR 2022
HR_fit_22 <- HR_fit %>%
  filter(Year == "2022")

#isolate HR 2023 G1
HR_fit_23_G1 <- HR_fit %>%
  filter(Year == "2023", Gen == "G1")

#isolate HR 2023 G2
HR_fit_23_G2 <- HR_fit %>%
  filter(Year == "2023", Gen == "G2")

#isolate all G1 together
HR_fit_G1 <- HR_fit %>%
  filter(Gen == "G1")

#isolate by year
HR_fit_23 <- HR_fit %>%
  filter(Year == "2023")

```

```{r}

HR_fit_22_unique <- HR_fit_22 %>%
  group_by(Donor, Recipient) %>%
  summarise(g0_msm = mean(msm_all, na.rm = TRUE), .groups = "drop")

HR_fit_23_G2 <- HR_fit_23_G2 %>%
  left_join(HR_fit_22_unique, by = c("Donor", "Recipient"))


```


Average based on paternal donor mean trait values
```{r}
##Obtain paternal genotypic values - this is what we are interested in
# Aggregate data by donor
HR_mean_donor_traits_22 <- HR_fit_22%>%
  group_by(Donor) %>%             # Group by donor
  summarise(
    closed_fruits = mean(closed_fruits, na.rm = TRUE),
    total_fruits = mean(total_fruits, na.rm = TRUE),
    filled_seeds = mean(filled_seeds, na.rm = TRUE),
    mean_seeds_per_fruit = mean(mean_seeds_per_fruit, na.rm = TRUE),
    fl_duration = mean(fl_duration, na.rm = TRUE),
    skel_dryweight_mg = mean(skel_dryweight_mg, na.rm = TRUE),
    msm_all = mean(msm_all, na.rm = TRUE),
    corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE),
    SLA_SEG = mean(SLA_SEG, na.rm = TRUE),
    d13C_SEG = mean(d13C_SEG, na.rm = TRUE),
    est_fecundity = mean(est_fecundity, na.rm = TRUE),
    survival = mean(survival, na.rm = TRUE),
    est_fitness = mean(est_fitness, na.rm = TRUE),
        count = n() 
  )

HR_mean_donor_traits_23_G1 <- HR_fit_23_G1%>%
  group_by(Donor) %>%             # Group by donor
  summarise(
    closed_fruits = mean(closed_fruits, na.rm = TRUE),
    total_fruits = mean(total_fruits, na.rm = TRUE),
    filled_seeds = mean(filled_seeds, na.rm = TRUE),
    mean_seeds_per_fruit = mean(mean_seeds_per_fruit, na.rm = TRUE),
    fl_duration = mean(fl_duration, na.rm = TRUE),
    skel_dryweight_mg = mean(skel_dryweight_mg, na.rm = TRUE),
    msm_all = mean(msm_all, na.rm = TRUE),
    corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE),
    SLA_SEG = mean(SLA_SEG, na.rm = TRUE),
    d13C_SEG = mean(d13C_SEG, na.rm = TRUE),
    est_fecundity = mean(est_fecundity, na.rm = TRUE),
    survival = mean(survival, na.rm = TRUE),
    est_fitness = mean(est_fitness, na.rm = TRUE),
        count = n() 
  )

HR_mean_donor_traits_23_G2 <- HR_fit_23_G2%>%
  group_by(Donor) %>%             # Group by donor
  summarise(
    closed_fruits = mean(closed_fruits, na.rm = TRUE),
    total_fruits = mean(total_fruits, na.rm = TRUE),
    filled_seeds = mean(filled_seeds, na.rm = TRUE),
    mean_seeds_per_fruit = mean(mean_seeds_per_fruit, na.rm = TRUE),
    fl_duration = mean(fl_duration, na.rm = TRUE),
    skel_dryweight_mg = mean(skel_dryweight_mg, na.rm = TRUE),
    msm_all = mean(msm_all, na.rm = TRUE),
    corolla_diam_mm_SEG = mean(corolla_diam_mm_SEG, na.rm = TRUE),
    SLA_SEG = mean(SLA_SEG, na.rm = TRUE),
    d13C_SEG = mean(d13C_SEG, na.rm = TRUE),
    est_fecundity = mean(est_fecundity, na.rm = TRUE),
    survival = mean(survival, na.rm = TRUE),
    est_fitness = mean(est_fitness, na.rm = TRUE),
    g0_msm = mean(g0_msm, na.rm = TRUE),
        count = n() 
  )
```

```{r}

correlation <- cor(HR_mean_donor_traits_23_G2$g0_msm, HR_mean_donor_traits_23_G2$msm_all, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

correlation <- cor(HR_mean_donor_traits_23_G2$g0_msm, HR_mean_donor_traits_23_G2$survival, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

correlation <- cor(HR_mean_donor_traits_23_G2$g0_msm, HR_mean_donor_traits_23_G2$est_fecundity, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

correlation <- cor(HR_mean_donor_traits_23_G2$g0_msm, HR_mean_donor_traits_23_G2$est_fitness, use = "complete.obs")
print(correlation) #slight positive correlation, fitness is pretty context specific

```


```{r}
# Save as a CSV file
write_csv(AC_mean_donor_traits_23_G2, here::here("data_sheets", "compiled_sheets", "AC_mean_donor_traits_23_G2"))

write_csv(BB_mean_donor_traits_23_G2, here::here("data_sheets", "compiled_sheets", "BB_mean_donor_traits_23_G2"))

write_csv(BO_mean_donor_traits_23_G2, here::here("data_sheets", "compiled_sheets", "BO_mean_donor_traits_23_G2"))

write_csv(HR_mean_donor_traits_23_G2, here::here("data_sheets", "compiled_sheets", "HR_mean_donor_traits_23_G2"))
```

