---
title: "BB_22_23_merge"
author: "Helen Payne"
date: "2024-06-05"
output:
  pdf_document: default
  html_document: default
---


```{r message = FALSE, warning = FALSE}
#Load Packages
library(tidyverse)
library(janitor)
library(here)
library(lubridate)
library(reshape2)
library(stringr)

```

Loading BB data from 2022 and 2023
```{r}
BB_2022_full <- read_csv(here::here("data_sheets", "compiled_sheets", "BB_mastersheet_full_2022.csv"))

BB_2022_fit <- read_csv(here::here("data_sheets", "compiled_sheets", "BB_mastersheet_Fitness-mains_2022.csv"))
  

BB_2023_full <- read_csv(here::here("data_sheets", "compiled_sheets", "BB_mastersheet_full_2023.csv"))

BB_2023_fit <- read_csv(here::here("data_sheets", "compiled_sheets", "BB_mastersheet_Fitness-mains_2023.csv"))

```
```{r}
#Rename a variable that had a typo: fruitprod -> fruitpod
BB_2023_fit <- BB_2023_fit %>%
  rename(surv_to_fruitpod = surv_to_fruitprod)

BB_2023_full <- BB_2023_full %>%
  rename(surv_to_fruitpod = surv_to_fruitprod)

BB_2022_full <- BB_2022_full %>%
  rename(surv_to_fruitpod = surv_to_fruitprod)

BB_2022_fit <- BB_2022_fit %>%
  rename(surv_to_fruitpod = surv_to_fruitprod)
```


Merging them into one large dataset
Full:
```{r}
BB_22_23_full <- full_join(BB_2023_full, BB_2022_full, by = c("Year", "Gen", "Location", "Sequence", "Donor", "Recipient", "Plant_ID", "F_plant", "Sow_Date", "Plant_Date", "FFD", "days_sow2flower", "days_plant2flower", "LFD", "fl_duration", "skel_dryweight_mg", "skel_dryweight_mg_SEG", "closed_fruits", "open_fruits", "filled_seeds", "total_fruits", "mean_seeds_per_fruit", "est_fecundity", "msm_all", "corolla_diam_mm", "corolla_diam_mm_SEG", "leaf_area_mm2", "leaf_dryweight_mg", "leaf_area_mm2_SEG", "leaf_dryweight_mg_SEG", "SLA_SEG", "SLA", "LMA_SEG", "LMA", "d13C", "surv_to_flower", "surv_to_fruitpod", "prod_closed_fruits", "prod_filled_seeds", "sample_weight_mg", "d13C_SEG"))
```

Fitness plants only:
```{r}
BB_22_23_fit <- full_join(BB_2023_fit, BB_2022_fit, by = c("Year", "Gen", "Location", "Sequence", "Donor", "Recipient", "Plant_ID", "F_plant", "Sow_Date", "Plant_Date", "FFD", "days_sow2flower", "days_plant2flower", "LFD", "fl_duration", "skel_dryweight_mg", "skel_dryweight_mg_SEG", "closed_fruits", "open_fruits", "filled_seeds", "total_fruits", "mean_seeds_per_fruit", "est_fecundity", "msm_all", "corolla_diam_mm", "corolla_diam_mm_SEG", "leaf_area_mm2", "leaf_dryweight_mg", "leaf_area_mm2_SEG", "leaf_dryweight_mg_SEG", "SLA_SEG", "SLA", "LMA_SEG", "LMA", "d13C", "surv_to_flower", "surv_to_fruitpod", "prod_closed_fruits", "prod_filled_seeds", "sample_weight_mg", "d13C_SEG"))
```

```{r}
BB_22_23_full_2 <- BB_2023_fit %>% 
  mutate(surv_to_fruitpod = replace_na(surv_to_fruitpod, 0))

```



Save these files
```{r}
write_csv(BB_22_23_fit, here::here("data_sheets", "compiled_sheets", "BB_22_23_fit.csv"))

write_csv(BB_22_23_full, here::here("data_sheets", "compiled_sheets", "BB_22_23_full.csv"))
```


